CREATE TABLE CUSTOMER (
    CustId NUMBER(5),
    CustName VARCHAR2(100),
    CustPhone VARCHAR2(20),
    CustEmail VARCHAR2(100),
    CustAddress VARCHAR2(255),
    CustPassword VARCHAR(15),
    
    CONSTRAINT custid_pk PRIMARY KEY (CustId),
    CONSTRAINT custname_nn CHECK (CustName IS NOT NULL),
    CONSTRAINT custphone_nn CHECK (CustPhone IS NOT NULL),
    CONSTRAINT custphone_uk UNIQUE (CustPhone),
    CONSTRAINT custaddress_nn CHECK (CustAddress IS NOT NULL),
    CONSTRAINT custpass_nn CHECK (CustPassword IS NOT NULL)
);

CREATE TABLE SUPPLIER (
    SupplierId NUMBER(5),
    SupplierName VARCHAR2(100) NOT NULL,
    SupplierContact VARCHAR2(100),
    SupplierPhone VARCHAR2(20),
    SupplierEmail VARCHAR2(100),
    SupplierType VARCHAR2(15),
    
    CONSTRAINT supplierid_pk PRIMARY KEY (SupplierId),
    CONSTRAINT suppliername_nn CHECK (SupplierName IS NOT NULL),
    CONSTRAINT supplierphone_nn CHECK (SupplierPhone IS NOT NULL),
    CONSTRAINT supplieremail_nn CHECK (SupplierEmail IS NOT NULL),
    CONSTRAINT suppliertype_nn CHECK (SupplierType IS NOT NULL),
    CONSTRAINT suppliertype_type CHECK (SupplierType IN ( 'LOCALFARM', 'DISTRIBUTOR'))
);

CREATE TABLE LOCALFARM (
    SupplierId NUMBER(5),
    FarmAddress VARCHAR2(255) NOT NULL,
    CONSTRAINT supplierid_pk1 PRIMARY KEY (SupplierId),
    CONSTRAINT supplierid_fk1 FOREIGN KEY (SupplierId) REFERENCES SUPPLIER(SupplierId) ON DELETE CASCADE,
    CONSTRAINT farmAddress_nn CHECK (FarmAddress IS NOT NULL)
);

CREATE TABLE DISTRIBUTOR (
    SupplierId NUMBER(5),
    BusinessLicenseNo VARCHAR2(50),
    DistributionCenterId VARCHAR2(50),
    LogisticPartner VARCHAR2(50),
    CONSTRAINT supplierid_pk2 PRIMARY KEY (SupplierId),
    CONSTRAINT supplierid_fk2 FOREIGN KEY (SupplierId) REFERENCES SUPPLIER(SupplierId) ON DELETE CASCADE,
    CONSTRAINT businesslicense_nn CHECK (BusinessLicenseNo IS NOT NULL)
);

CREATE TABLE STAFFS (
    StaffId NUMBER(5),
    StaffName VARCHAR2(100),
    StaffSalary NUMBER(10, 2),
    StaffAddress VARCHAR2(255),
    StaffEmail VARCHAR2(100),
    StaffPhone VARCHAR2(20),
    ManagerId NUMBER(5),
    StaffPassword VARCHAR2(15),
    StaffRole VARCHAR2(20) DEFAULT 'STAFF',
    HireDate DATE DEFAULT SYSDATE,
    
    CONSTRAINT staffid_pk PRIMARY KEY (StaffId),
    CONSTRAINT staffname_nn CHECK (StaffName IS NOT NULL),
    CONSTRAINT managerid_fk FOREIGN KEY (ManagerId) REFERENCES STAFFS(StaffId) ON DELETE SET NULL,
    CONSTRAINT staffemail_nn CHECK (StaffEmail IS NOT NULL),
    CONSTRAINT staffemail_uk UNIQUE (StaffEmail),
    CONSTRAINT staffpassword_nn CHECK (StaffPassword IS NOT NULL),
    CONSTRAINT staffrole_ck CHECK (StaffRole IN ('ADMIN', 'STAFF'))
);


CREATE TABLE FRUITS (
    FruitId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FruitName VARCHAR2(100) NOT NULL,
    CostPrice NUMBER(10, 2), -- How much you bought it for (needed for profit calc)
    FruitPrice NUMBER(10, 2), -- How much you sell it for
    QuantityStock NUMBER DEFAULT 0,
    Unit VARCHAR2(20) DEFAULT 'KG', -- 'KG', 'PACK', 'PCS' (Vital: selling 1 pack is diff from 1 kg)
    Category VARCHAR2(50), -- 'LOCAL', 'IMPORTED', 'SEASONAL'
    ReorderLevel NUMBER DEFAULT 10, -- Alert when stock drops below this
    ExpiryDate DATE, -- Fruits rot. You need to know when to throw them out.
    ImageURL VARCHAR2(255), -- For the web UI
    
    SupplierId NUMBER,
    CONSTRAINT fk_fruit_supplier FOREIGN KEY (SupplierId) REFERENCES SUPPLIER(SupplierId)
);

CREATE TABLE ORDERS (
    OrderId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    OrderDate DATE DEFAULT SYSDATE,
    CustId NUMBER,
    StaffId NUMBER,
    -- TRANSACTION DETAILS
    TotalAmount NUMBER(10, 2) DEFAULT 0, -- Store the final total for faster reporting
    PaymentMethod VARCHAR2(50), -- 'CASH', 'QR', 'CARD'
    OrderStatus VARCHAR2(20) DEFAULT 'COMPLETED', -- 'COMPLETED', 'CANCELLED'
    
    CONSTRAINT fk_order_cust FOREIGN KEY (CustId) REFERENCES CUSTOMER(CustId),
    CONSTRAINT fk_order_staff FOREIGN KEY (StaffId) REFERENCES STAFFS(StaffId)
);

CREATE TABLE ORDERDETAILS (
    OrderDetailsId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    OrderId NUMBER,
    FruitId NUMBER,
    Quantity NUMBER,
    
    -- HISTORICAL DATA PROTECTION
    UnitPriceSnapshot NUMBER(10, 2), -- CRITICAL: The price *at the moment* of sale. 
    Subtotal NUMBER(10, 2), -- (Quantity * UnitPriceSnapshot)
    
    CONSTRAINT fk_detail_order FOREIGN KEY (OrderId) REFERENCES ORDERS(OrderId),
    CONSTRAINT fk_detail_fruit FOREIGN KEY (FruitId) REFERENCES FRUITS(FruitId)
);

-- 2. Insert Mock Data

-- Fruits
INSERT INTO FRUITS (FruitName, CostPrice, FruitPrice, QuantityStock, Unit, Category, ReorderLevel, SupplierId) 
VALUES ('Mango Susu', 8.00, 15.00, 50, 'KG', 'LOCAL', 10, 1);

INSERT INTO FRUITS (FruitName, CostPrice, FruitPrice, QuantityStock, Unit, Category, ReorderLevel, SupplierId) 
VALUES ('Durian Musang King', 40.00, 65.00, 20, 'KG', 'LOCAL', 5, 1);

INSERT INTO FRUITS (FruitName, CostPrice, FruitPrice, QuantityStock, Unit, Category, ReorderLevel, SupplierId) 
VALUES ('Fuji Apple', 1.50, 3.00, 100, 'PCS', 'IMPORTED', 20, 2);

-- Orders (Mocking a transaction)
INSERT INTO ORDERS (OrderDate, CustId, StaffId, TotalAmount, PaymentMethod, OrderStatus) 
VALUES (SYSDATE, 1, 2, 30.00, 'CASH', 'COMPLETED');

INSERT INTO ORDERDETAILS (OrderId, FruitId, Quantity, UnitPriceSnapshot, Subtotal) 
VALUES (1, 1, 2, 15.00, 30.00); -- Bought 2kg Mango @ 15.00 each

COMMIT;