<?php
session_start();
require_once('db_conn.php');

if (!isset($_SESSION['user_id'])) { header("Location: login.php"); exit(); }
include('includes/header.php');

// --- PHP: PROCESS SUBMISSION ---
if (isset($_POST['submit_sale'])) {
    // 1. Get Form Data
    $cust_id = $_POST['cust_id'];
    $pay_method = $_POST['payment_method'];
    $staff_id = $_SESSION['user_id'];
    
    // 'items' will be an array sent from the hidden inputs generated by JS
    // Structure: $_POST['items'][0]['id'], $_POST['items'][0]['qty']...
    $items = isset($_POST['items']) ? $_POST['items'] : [];

    if (count($items) > 0) {
        // 2. Calculate Grand Total Server-Side (Security measure)
        $grand_total = 0;
        $valid_items = [];

        foreach ($items as $item) {
            $fid = $item['id'];
            $qty = $item['qty'];

            // Get latest price & stock from DB
            $sql_check = "SELECT FruitPrice, QuantityStock FROM FRUITS WHERE FruitId = :fid";
            $s_check = oci_parse($dbconn, $sql_check);
            oci_bind_by_name($s_check, ":fid", $fid);
            oci_execute($s_check);
            $fruit_data = oci_fetch_array($s_check, OCI_ASSOC);

            if ($fruit_data) {
                if ($qty > $fruit_data['QUANTITYSTOCK']) {
                    echo "<script>Swal.fire('Stock Error', 'Insufficient stock for one of the items.', 'error');</script>";
                    exit(); // Stop process
                }
                $grand_total += ($fruit_data['FRUITPRICE'] * $qty);
                $valid_items[] = [
                    'id' => $fid,
                    'qty' => $qty,
                    'price' => $fruit_data['FRUITPRICE']
                ];
            }
        }

        // 3. Insert Order Header
        $new_order_id = 0;
        $sql_ord = "INSERT INTO ORDERS (OrderId, OrderDate, CustId, StaffId, TotalAmount, PaymentMethod, OrderStatus) 
                    VALUES (order_id_seq.NEXTVAL, SYSDATE, :cid, :sid, :tot, :pay, 'COMPLETED') RETURNING OrderId INTO :new_oid";
        
        $stmt_ord = oci_parse($dbconn, $sql_ord);
        oci_bind_by_name($stmt_ord, ":cid", $cust_id);
        oci_bind_by_name($stmt_ord, ":sid", $staff_id);
        oci_bind_by_name($stmt_ord, ":tot", $grand_total);
        oci_bind_by_name($stmt_ord, ":pay", $pay_method);
        oci_bind_by_name($stmt_ord, ":new_oid", $new_order_id, -1, SQLT_INT);
        
        if (oci_execute($stmt_ord, OCI_NO_AUTO_COMMIT)) {
            
            // 4. Loop & Insert Details + Update Stock
            $success = true;
            foreach ($valid_items as $v_item) {
                // Insert Detail
                $sql_dtl = "INSERT INTO ORDERDETAILS (OrderDetailsId, OrderId, FruitId, Quantity) 
                            VALUES (orderdtl_id_seq.NEXTVAL, :oid, :fid, :qty)";
                $stmt_dtl = oci_parse($dbconn, $sql_dtl);
                oci_bind_by_name($stmt_dtl, ":oid", $new_order_id);
                oci_bind_by_name($stmt_dtl, ":fid", $v_item['id']);
                oci_bind_by_name($stmt_dtl, ":qty", $v_item['qty']);
                if (!oci_execute($stmt_dtl, OCI_NO_AUTO_COMMIT)) $success = false;

                // Update Stock
                $sql_upd = "UPDATE FRUITS SET QuantityStock = QuantityStock - :qty WHERE FruitId = :fid";
                $stmt_upd = oci_parse($dbconn, $sql_upd);
                oci_bind_by_name($stmt_upd, ":qty", $v_item['qty']);
                oci_bind_by_name($stmt_upd, ":fid", $v_item['id']);
                if (!oci_execute($stmt_upd, OCI_NO_AUTO_COMMIT)) $success = false;
            }

            if ($success) {
                oci_commit($dbconn);
                echo "<script>Swal.fire({ title: 'Success!', text: 'Order #$new_order_id completed.', icon: 'success' }).then(() => { window.location = 'orders.php'; });</script>";
            } else {
                oci_rollback($dbconn);
                echo "<script>Swal.fire('Error', 'Transaction Failed during detail insertion.', 'error');</script>";
            }
        } else {
            $e = oci_error($stmt_ord);
            echo "<script>Swal.fire('Error', 'Header Failed: " . $e['message'] . "', 'error');</script>";
        }
    } else {
        echo "<script>Swal.fire('Empty Cart', 'Please add items to the cart first.', 'warning');</script>";
    }
}
?>

<style>
    .pos-card { background: rgba(255, 255, 255, 0.95); border-radius: 20px; box-shadow: 0 10px 30px rgba(0,0,0,0.15); border: 1px solid rgba(255,255,255,0.5); }
    .cart-card { background: #2c3e50; color: #fff; border-radius: 20px; box-shadow: 0 10px 30px rgba(0,0,0,0.3); min-height: 500px; display: flex; flex-direction: column; }
    .table-cart { color: white; font-size: 0.9rem; }
    .table-cart th { border-bottom: 1px solid rgba(255,255,255,0.2); }
    .table-cart td { border-bottom: 1px solid rgba(255,255,255,0.1); vertical-align: middle; }
    .total-display { font-size: 2.5rem; font-weight: bold; color: #ffc107; text-shadow: 0 2px 4px rgba(0,0,0,0.5); }
    .btn-remove { color: #ff6b6b; cursor: pointer; transition: 0.3s; }
    .btn-remove:hover { color: #ff0000; transform: scale(1.2); }
</style>

<div class="container mt-4">
    <div class="row">
        <div class="col-12 mb-3">
            <h2 class="text-white fw-bold text-shadow"><i class="fas fa-cash-register me-2"></i>New Sale</h2>
        </div>

        <div class="col-md-6">
            <div class="card p-4 pos-card h-100">
                <h5 class="text-secondary fw-bold mb-3">1. Add Items</h5>
                
                <div class="mb-3">
                    <label class="form-label fw-bold">Select Product</label>
                    <select id="fruitSelect" class="form-select">
                        <option value="" data-price="0" data-stock="0">-- Select Fruit --</option>
                        <?php
                        $s2 = oci_parse($dbconn, "SELECT FruitId, FruitName, FruitPrice, QuantityStock FROM FRUITS WHERE QuantityStock > 0 ORDER BY FruitName");
                        oci_execute($s2);
                        while ($r2 = oci_fetch_array($s2, OCI_ASSOC)) { 
                            echo "<option value='".$r2['FRUITID']."' data-name='".$r2['FRUITNAME']."' data-price='".$r2['FRUITPRICE']."' data-stock='".$r2['QUANTITYSTOCK']."'>";
                            echo $r2['FRUITNAME']." (RM ".$r2['FRUITPRICE']." | Stock: ".$r2['QUANTITYSTOCK'].")";
                            echo "</option>"; 
                        }
                        ?>
                    </select>
                </div>

                <div class="row mb-3">
                    <div class="col-6">
                        <label class="form-label fw-bold">Quantity</label>
                        <input type="number" id="qtyInput" class="form-control" value="1" min="1">
                    </div>
                    <div class="col-6 d-flex align-items-end">
                        <button type="button" class="btn btn-primary w-100 fw-bold" onclick="addToCart()">
                            <i class="fas fa-plus me-2"></i> Add to List
                        </button>
                    </div>
                </div>

                <hr>

                <form method="POST" id="salesForm">
                    <h5 class="text-secondary fw-bold mb-3">2. Transaction Details</h5>
                    
                    <div class="mb-3">
                        <label class="form-label fw-bold">Customer</label>
                        <select name="cust_id" class="form-select" required>
                            <option value="">-- Select Customer --</option>
                            <?php
                            $s1 = oci_parse($dbconn, "SELECT CustId, CustName FROM CUSTOMER ORDER BY CustName");
                            oci_execute($s1);
                            while ($r1 = oci_fetch_array($s1, OCI_ASSOC)) { echo "<option value='".$r1['CUSTID']."'>".$r1['CUSTNAME']."</option>"; }
                            ?>
                        </select>
                    </div>

                    <div class="mb-4">
                        <label class="form-label fw-bold">Payment Method</label>
                        <select name="payment_method" class="form-select">
                            <option value="CASH">Cash</option>
                            <option value="QR">QR Pay</option>
                            <option value="CARD">Debit/Credit Card</option>
                        </select>
                    </div>

                    <div id="hiddenItemsContainer"></div>

                    <button type="submit" name="submit_sale" class="btn btn-warning w-100 btn-lg fw-bold shadow">
                        <i class="fas fa-check-double me-2"></i> CONFIRM PURCHASE
                    </button>
                </form>
            </div>
        </div>

        <div class="col-md-6 mt-4 mt-md-0">
            <div class="card p-4 cart-card">
                <h5 class="border-bottom pb-2 mb-3"><i class="fas fa-shopping-cart me-2"></i>Current Order List</h5>
                
                <div class="flex-grow-1 overflow-auto" style="max-height: 350px;">
                    <table class="table table-borderless table-cart">
                        <thead>
                            <tr>
                                <th>Item Name</th>
                                <th class="text-center">Qty</th>
                                <th class="text-end">Subtotal</th>
                                <th class="text-center">X</th>
                            </tr>
                        </thead>
                        <tbody id="cartTableBody">
                            <tr><td colspan="4" class="text-center text-muted fst-italic mt-3">Cart is empty...</td></tr>
                        </tbody>
                    </table>
                </div>

                <div class="mt-auto border-top border-secondary pt-3 text-center">
                    <small class="text-white-50 text-uppercase">Grand Total</small>
                    <div class="total-display" id="grandTotalDisplay">RM 0.00</div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    let cart = []; // Array to store items

    function addToCart() {
        const fruitSelect = document.getElementById("fruitSelect");
        const qtyInput = document.getElementById("qtyInput");
        const selectedOption = fruitSelect.options[fruitSelect.selectedIndex];

        // Validation
        if (fruitSelect.value === "") { Swal.fire('Oops', 'Please select a fruit!', 'warning'); return; }
        
        const id = selectedOption.value;
        const name = selectedOption.getAttribute("data-name");
        const price = parseFloat(selectedOption.getAttribute("data-price"));
        const stock = parseInt(selectedOption.getAttribute("data-stock"));
        const qty = parseInt(qtyInput.value);

        if (qty <= 0) { Swal.fire('Oops', 'Quantity must be at least 1.', 'warning'); return; }
        if (qty > stock) { Swal.fire('Stock Alert', 'Not enough stock! Available: ' + stock, 'error'); return; }

        // Check if item already exists in cart
        const existingItem = cart.find(item => item.id === id);
        if (existingItem) {
            if (existingItem.qty + qty > stock) {
                Swal.fire('Stock Alert', 'Total quantity exceeds stock!', 'error'); return;
            }
            existingItem.qty += qty;
        } else {
            cart.push({ id, name, price, qty, stock });
        }

        renderCart();
        
        // Reset Inputs
        fruitSelect.value = "";
        qtyInput.value = 1;
    }

    function removeFromCart(index) {
        cart.splice(index, 1);
        renderCart();
    }

    function renderCart() {
        const tbody = document.getElementById("cartTableBody");
        const hiddenContainer = document.getElementById("hiddenItemsContainer");
        const totalDisplay = document.getElementById("grandTotalDisplay");
        
        tbody.innerHTML = "";
        hiddenContainer.innerHTML = "";
        let grandTotal = 0;

        if (cart.length === 0) {
            tbody.innerHTML = "<tr><td colspan='4' class='text-center text-muted fst-italic'>Cart is empty...</td></tr>";
        }

        cart.forEach((item, index) => {
            const subtotal = item.price * item.qty;
            grandTotal += subtotal;

            // 1. Update Visual Table
            const row = `
                <tr>
                    <td>${item.name} <br><small class="text-white-50">RM ${item.price.toFixed(2)}/unit</small></td>
                    <td class="text-center">${item.qty}</td>
                    <td class="text-end">RM ${subtotal.toFixed(2)}</td>
                    <td class="text-center"><i class="fas fa-trash-alt btn-remove" onclick="removeFromCart(${index})"></i></td>
                </tr>
            `;
            tbody.innerHTML += row;

            // 2. Create Hidden Inputs for PHP
            // name="items[0][id]", name="items[0][qty]"
            const inputId = document.createElement("input");
            inputId.type = "hidden";
            inputId.name = `items[${index}][id]`;
            inputId.value = item.id;

            const inputQty = document.createElement("input");
            inputQty.type = "hidden";
            inputQty.name = `items[${index}][qty]`;
            inputQty.value = item.qty;

            hiddenContainer.appendChild(inputId);
            hiddenContainer.appendChild(inputQty);
        });

        totalDisplay.innerText = "RM " + grandTotal.toFixed(2);
    }
</script>

</body>
</html>